@ECHO OFF

SET ILASM="%WINDIR%\Microsoft.NET\Framework\v4.0.30319\ilasm.exe"
SET CLASS_NAME=SmartCalc
SET SOURSE_NAME=%CLASS_NAME%.il
SET EXEC_NAME=%CLASS_NAME%.exe

%ILASM% %SOURSE_NAME%

IF ERRORLEVEL 1 GOTO :FAIL

%EXEC_NAME%
GOTO :EOF

:FAIL
ECHO Build has failed...
